version: '3'
services:
  # web:
  #   container_name: web
  #   build: .
  #   command: npm run start:dev
  #   env_file: .env
  #   environment:
  #     - DB_HOSTNAME=localhost
  #     - DB_PORT=$DB_PORT
  #     - DB_USERNAME=$DB_USERNAME
  #     - DB_PASSWORD=$DB_PASSWORD
  #     - DB_NAME=$DB_NAME
  #     - JWT_SECRET=$JWT_SECRET
  #   volumes:
  #     - .:/usr/app/
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: 'postgres:13'
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/data/db
    environment:
      - POSTGRES_USERNAME=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "5432:5432"
    # networks:
      # - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
